import { ReactNode } from 'react'
import { useRouter } from 'next/router'
import Script from 'next/script'
import Head from 'next/head'
import Box from '@mui/material/Box'
import Container from '@mui/material/Container'
import Header from '@/components/regions/Header'
import Footer from '@/components/regions/Footer'
import { createTheme, ThemeProvider } from '@mui/material/styles'
import '@fontsource/poppins/200.css'
import '@fontsource/poppins/300.css'
import '@fontsource/poppins/700.css'

type Props = {
  children?: ReactNode
}

const mdTheme = createTheme({
  palette: {
    primary: { main: '#2A558C' }
  }
})

export default function Layout({ children }: Props) {
  const route = useRouter()

  return (
    <>
      <Script
        src="https://www.googletagmanager.com/gtag/js?id=G-YS4SJXC4C5"
        strategy="afterInteractive"
      />
      <Script id="google-analytics" strategy="afterInteractive">
        {`
          window.dataLayer = window.dataLayer || [];
          function gtag(){window.dataLayer.push(arguments);}
          gtag('js', new Date());

          gtag('config', 'G-YS4SJXC4C5');
        `}
      </Script>
      <ThemeProvider theme={mdTheme}>
        <Head>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Box id="app">
          <div className="stars" id="stars-sm"></div>
          <div className="stars" id="stars-md"></div>
          <div className="stars" id="stars-lg"></div>
          <Header />
          <Container sx={{ paddingX: 5 }} disableGutters={true}>
            <main>{children}</main>
          </Container>
          {route.pathname !== '/' && <Footer />}
        </Box>
      </ThemeProvider>
    </>
  )
}
